TodoApp/urls.py
from django.urls import path
from . import views
from .views import RegisterUser, logout_user, LoginUser, about, TaskListView, CreateTaskView, ShowTask, \
    TaskToggleDoneView, TaskDeleteView

urlpatterns = [
    path('', TaskListView.as_view(), name='home'),
    path('about/', about, name='about'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('addtask/', CreateTaskView.as_view(), name='add_task'),
    path('task/<slug:task_slug>/', ShowTask.as_view(), name='task'),
    path('task/<slug:task_slug>/toggle/', TaskToggleDoneView.as_view(), name='task_toggle'),
    path('task/<slug:task_slug>/delete/', TaskDeleteView.as_view(), name='task_delete')
]

TodoAppProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from TodoAppProject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    path('', include('TodoApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TodoApp/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify


class Task(models.Model):
    HIGH = 1
    MEDIUM = 2
    LOW = 3

    PRIORITY_CHOICES = [
        (HIGH, 'High'),
        (MEDIUM, 'Medium'),
        (LOW, 'Low'),
    ]

    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=255, verbose_name="Название")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    description = models.TextField(blank=True, verbose_name="Описание")

    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=MEDIUM,
        verbose_name='Приоритет'
    )

    deadline = models.DateTimeField(null=True, blank=True, verbose_name="Дедлайн")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='tasks',
    )

    is_done = models.BooleanField(default=False, verbose_name="Решена")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('task', kwargs={'task_slug': self.slug})

    def is_overdue(self):
        return self.deadline and self.deadline < timezone.now()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

            unique_slug = self.slug
            counter = 1

            while Task.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{self.slug}-{counter}"
                counter += 1
            self.slug = unique_slug

        super().save(*args, **kwargs)

    class Meta:
        ordering = ('priority', 'deadline')
        verbose_name = 'Задачи'
        verbose_name_plural = 'Задачи'

TodoApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from TodoApp.models import Task


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'priority', 'deadline')


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

TodoApp/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, CreateView, DetailView

from TodoApp.forms import *
from TodoApp.models import Task


class TaskListView(ListView):
    model = Task
    template_name = 'TodoApp/index.html'
    context_object_name = 'tasks'
    paginate_by = 5

    def get_queryset(self):
        status = self.request.GET.get('status', 'all')

        if self.request.user.is_authenticated:
            queryset = Task.objects.filter(user=self.request.user)
        else:
            queryset = Task.objects.none()

        if status == 'done':
            queryset = queryset.filter(is_done=True)
        elif status == 'not_done':
            queryset = queryset.filter(is_done=False)
        elif status == 'overdue':
            queryset = queryset.filter(is_done=False, deadline__lt=timezone.now())

        return queryset

class TaskToggleDoneView(View):
    def post(self, request, task_slug):
        task = get_object_or_404(Task, slug=task_slug, user=request.user)
        task.is_done = not task.is_done
        task.save(update_fields=["is_done"])
        return redirect('home')

class TaskDeleteView(LoginRequiredMixin, View):
    def post(self, request, task_slug):
        task = get_object_or_404(Task, slug=task_slug, user=request.user)
        task.delete()
        return redirect('home')

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'TodoApp/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'TodoApp/login.html'

    def get_success_url(self):
        return reverse_lazy('home')

class CreateTaskView(LoginRequiredMixin, CreateView):
    form_class = AddTaskForm
    template_name = 'TodoApp/addpage.html'
    success_url = reverse_lazy('home')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ShowTask(DetailView):
    model = Task
    template_name = 'TodoApp/task.html'
    slug_url_kwarg = 'task_slug'
    context_object_name = 'task'

def about(request):
    return render(request, 'TodoApp/about.html')

def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

def logout_user(request):
    logout(request)
    return redirect('login')

TodoApp/templates/TodoApp/about.html
{% extends 'TodoApp/base.html' %}
{% load static %}
{% block title %}О сайте{% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'TodoApp/css/about.css' %}">{% endblock %}
{% block content %}
    <section class="about-text">
        <div>
            <h2>О сайте TodoApp</h2>
            <p><span>TodoApp</span> — это онлайн-приложение для управления задачами, созданное с целью помочь вам повысить продуктивность и организовать свою работу.
                Мы понимаем, как сложно иногда держать в голове все важные дела, особенно когда у вас есть множество задач, проектов и сроков.
                Поэтому <span>TodoApp</span> — это идеальное решение для людей, которым нужно контролировать свои задачи, не упуская из виду ни одну деталь.</p>
            <h3>Что такое TodoApp?</h3>
            <p><span>TodoApp</span> — это удобный инструмент для планирования. С помощью этого сервиса вы можете:</p>
            <ul>
                <li>
                    <p>Легко создавать задачи, указывая важную информацию: название, описание, срок исполнения и приоритет</p>
                </li>
                <li>
                    <p>Отслеживать статус задач: решены они или ещё нет</p>
                </li>
                <li>
                    <p>Просматривать задачи, которые были просрочены</p>
                </li>
            </ul>
            <h3>Особенности TodoApp</h3>
            <ul>
                <li>
                    <p><span>Интуитивно понятный интерфейс:</span> Для нас важно, чтобы даже новые пользователи могли сразу начать использовать приложение без лишних объяснений.
                        Мы сделали так, чтобы интерфейс был максимально простым и понятным</p>
                </li>
                <li>
                    <p><span>Поддержка приоритетов и дедлайнов:</span> Вы можете назначать приоритеты задачам и устанавливать дедлайны, чтобы не упустить важные моменты</p>
                </li>
                <li>
                    <p><span>Просроченные задачи:</span> Система автоматически отслеживает просроченные задачи и отображает их в отдельной категории, чтобы вы могли быстро на них отреагировать</p>
                </li>
            </ul>
            <h3>Как это работает?</h3>
            <ul>
                <li>
                    <p><span>Создание задачи:</span> Чтобы добавить задачу, достаточно нажать на кнопку "Добавить задачу", ввести название и описание,
                        установить дедлайн и приоритет</p>
                </li>
                <li>
                    <p><span>Фильтрация задач:</span> Вы можете отсортировать задачи по их статусу: решённые, нерешённые или просроченные</p>
                </li>
            </ul>
        </div>
    </section>
{% endblock %}

TodoApp/templates/TodoApp/addpage.html
{% extends 'TodoApp/base.html' %}
{% block title %}Добавление задачи{% endblock %}
{% load static %}
{% block head %}<link rel="stylesheet" href="{% static 'TodoApp/css/addpage.css' %}">{% endblock %}
{% block content %}
    <form action="{% url 'add_task' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

        <div>{{ form.non_field_errors }}</div>
{% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
{% endfor %}
    <button type="submit" class="submit-btn">Добавить</button>
    </form>
{% endblock %}

TodoApp/templates/TodoApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Добавляем для адаптивности -->
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'TodoApp/css/base.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'TodoApp/images/logo.ico' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
    <header>
        <nav>
            <ul class="list">
                <li><a href="{% url 'home' %}">Главная страница</a></li>
                <li><a href="{% url 'about' %}">О сайте</a></li>
            </ul>
            <ul class="list">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="{% url 'logout' %}">Выйти</a></li>
                {% else %}
                    <li><a href="{% url 'register' %}">Регистрация</a></li>
                    <li><a href="{% url 'login' %}">Войти</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="footer-content">
            <div class="footer-left">
                <p>Все права защищены.</p>
                <p><a href="#">Политика конфиденциальности</a> | <a href="#">Пользовательское соглашение</a></p>
            </div>
            <div class="footer-right">
                <p>Контакты: <a href="mailto:info@todoapp.com">just51290@mail.ru</a></p>
            </div>
        </div>
    </footer>
</body>
</html>

TodoApp/templates/TodoApp/index.html
{% extends 'TodoApp/base.html' %}
{% load static %}
{% block title %}Главная страница{% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'TodoApp/css/index.css' %}">{% endblock %}
{% block content %}
    <section>
        <div class="container big-green-button green-button">
            <a href="{% url 'add_task' %}">Добавить задачу</a>
        </div>
    </section>
    <section class="main-section">
        {% if not user.is_authenticated %}
            <div class="warning-block">
                <p class="warning-text">Вы не авторизовались. Чтобы вы могли создавать задачи, вам необходимо авторизоваться.
                    Для этого зарегистрируйтесь на сайте, либо войдите</p>
            </div>
        {% else %}
        <div class="filter-section green-button">
            <a href="?status=all" class="filter-btn">Все</a>
            <a href="?status=done" class="filter-btn">Решённые</a>
            <a href="?status=not_done" class="filter-btn">Нерешённые</a>
            <a href="?status=overdue" class="filter-btn">Просроченные</a>
        </div>

        {% for task in tasks %}
            <div href="#" class="task-item
            {% if task.priority == 1 %} task-high
            {% elif task.priority == 2 %} task-medium
            {% else %} task-low
            {% endif %}">
                <h2>{{ task.title }}</h2>
                <p>{{ task.description|truncatechars:100 }}</p>
                <p>Дедлайн: {{ task.deadline }}</p>
                <p>Готовность: {{ task.is_done }}</p>
                <div class="task-actions">
                    <form method="post" action="{% url 'task_toggle' task.slug %}">
                        {% csrf_token %}
                        <button type="submit">
                            {% if task.is_done %}↩ Не готово{% else %}✔ Готово{% endif %}
                        </button>
                    </form>

                    <a href="{{ task.get_absolute_url }}" class="btn-details">
                        📄 Подробнее
                    </a>

                    <form method="post" action="{% url 'task_delete' task.slug %}">
                        {% csrf_token %}
                        <button type="submit">✖ Удалить</button>
                    </form>
                </div>
            </div>
        {% endfor %}
        {% endif %}
        {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1&status={{ request.GET.status|default:'all' }}">&laquo; Первая</a>
                <a href="?page={{ page_obj.previous_page_number }}&status={{ request.GET.status|default:'all' }}">Предыдущая</a>
            {% endif %}

            <span class="current">
                Страница {{ page_obj.number }} из {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&status={{ request.GET.status|default:'all' }}">Следующая</a>
                <a href="?page={{ paginator.num_pages }}&status={{ request.GET.status|default:'all' }}">Последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}

    </section>
{% endblock %}

TodoApp/templates/TodoApp/login.html
{% extends 'TodoApp/base.html' %}
{% load static %}
{% block title %}Вход{% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'TodoApp/css/login.css' %}">{% endblock %}
{% block content %}
    <div class="form-container">
        <h1 class="form-title">Вход</h1>

        <form method="post">
            {% csrf_token %}

            <div class="form-error">{{ form.non_field_errors }}</div>

            {% for f in form %}
                <div class="form-group">
                    <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
                    {{ f }}
                    <div class="form-error">{{ f.errors }}</div>
                </div>
            {% endfor %}

            <button type="submit" class="submit-btn">Войти</button>
            <div class="register-link">
                <p>Нет аккаунта? <a href="{% url 'register' %}">Зарегистрироваться</a></p>
            </div>
        </form>
    </div>
{% endblock %}

TodoApp/templates/TodoApp/register.html
{% extends 'TodoApp/base.html' %}
{% load static %}
{% block title %}Регистрация{% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'TodoApp/css/register.css' %}">{% endblock %}
{% block content %}
    <div class="form-container">
        <h1 class="form-title">Регистрация</h1>

        <form method="post">
            {% csrf_token %}

            {% for f in form %}
            <div class="form-group">
                <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
                {{ f }}
                <div class="form-error">{{ f.errors }}</div>
            </div>
            {% endfor %}

            <button type="submit" class="submit-btn">Регистрация</button>
        </form>
    </div>
{% endblock %}

TodoApp/templates/TodoApp/task.html
{% extends 'TodoApp/base.html' %}
{% load static %}
{% block title %}{{ task.slug }}{% endblock %}
{% block head %}<link rel="stylesheet" href="{% static 'TodoApp/css/task.css' %}">{% endblock %}
{% block content %}
    <section class="task-detail">
        <h1 class="task-title">{{ task.slug }}</h1>

        <p><strong>Описание:</strong></p>
        <p class="task-description">{{ task.description }}</p>

        <p><strong>Приоритет:</strong> <span class="task-priority">{{ task.get_priority_display }}</span></p>

        <p><strong>Дедлайн:</strong> <span class="task-deadline">{{ task.deadline }}</span></p>

        <p><strong>Статус:</strong>
            <span class="task-status {% if task.is_done %}done{% else %}not-done{% endif %}">
                {% if task.is_done %}Готово{% else %}Не готово{% endif %}
            </span>
        </p>
    </section>
{% endblock %}